[package]
name = "vscr-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
vscr-core = { path = "../vscr-core" }
vscr-data = { path = "../vscr-data" }
vscr-debug = { path = "../vscr-debug" }
